name: bump-version
on:
  pull_request:
    types: [opened, reopened]


jobs:
  get-version:
    name: get version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read package.json
        id: package
        uses: traversals-analytics-and-intelligence/file-reader-action@master
        with:
          file: ./package.json
      - name: Echo package.json
        run: echo "${{ steps.template.outputs.content }}"
