name: bump-version
on:
  pull_request:
    types: [opened, reopened]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  get-version:
    name: get version
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Read package.json
        id: package
        uses: traversals-analytics-and-intelligence/file-reader-action@master
        with:
          file: ./package.json
      - name: Echo package.json
        run: echo "${{ fromJSON(steps.package.outputs.content).version }}"
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.19.0
