name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:  
  hello-world:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  trigger-from-other-repo:        
    runs-on: ubuntu-latest
    steps:
      - run: |
            curl -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
            -s -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/leandra00/test-actions2/commits \
            | grep -E -m 1 sha \
            | awk 'BEGIN { FS = "\""; } { print $4 }'
#      - uses: actions/github-script@v6
#        with:
#          github-token: ${{ secrets.PAT_TOKEN }}
#          script: |
#            await github.rest.actions.createWorkflowDispatch({
#                owner: 'leandra00',
#                repo: 'test-actions2',
#                workflow_id: 'bundle.yml',
#                ref: 'main',
#              })
            
